### PR TITLE
WoW support, Region support, Full data on return

### PR DESCRIPTION
**Pull request by TheJaydox**
I was looking or a OAuth client for PHP + BNet, however I found WoW support was needed, so I added/updated a few items:
- Added region support.
- Added wow support.
- Changed return to get full use of returned data.
- Test updated.
- Readme updated.

-- Laravel untested with changes.
> I was not sure on testing with Laravel atm.

I changed the way the return happened, as there can be multiple 'characters' for example with WoW, the changes are to return the full data from the API request, returning only the first [0] I found gave me a Level 1 character.  The down side is the returns are no longer `$user->id;` and instead would be (using the test for example) `$user->data[0]['id'];`

Hope these changes are not too drastic, my primary goal was adding in WoW support :)

### CODE REVIEW

**Comment by tpavlek** [comment]
Thanks for this!

I'll take a look at the specifics when I get in to work, but it looks like
a good pull!

**Comment by tpavlek** [comment]
Hi!

So this code is now merged in (in one form or another). There was a lot I liked, but as I looked closer there really were quite a few differences between WoW and SC2, so it didn't make sense to have them on the same providers/entities.

As a result, you can now use either a `SC2Provider` or a `WowProvider`, which will then return an `SC2User` or `WowUser` respectively. I really did like my API of public properties on the `SC2User` so I definitely wanted to maintain that, but they didn't match at all with the difference concerns of a `WowUser`.

The README contains some updated documentation about how to use these new pieces, so if you have any questions just ask!

Since this is a backwards-breaking change and I follow semantic versioning, this will mean the release tonight is 5.0.0, so if you composer.json is requiring ^4.0.0 you'll need to update that to pull the new version.

Thanks for the pull!

**Comment by TheJaydox** [comment]
Awesome & great idea with the split :)

**Comment by tpavlek** [comment]
When you get a chance do double check that it works as expected. I don't
have, nor know anyone with a WoW account so testing that component didn't
really do much.

**Comment by TheJaydox** [comment]
Tested this morning for WoW, works great.  :)

**Pull request merged**
