### PR TITLE
Add region support for getBaseAuthorizationUrl & getBaseAccessTokenUrl

### PR DESCRIPTION
**Pull request by gsdevme**

### CODE REVIEW

**Comment by tpavlek** [comment]
I generally prefer string interpolation, because I find it both cleaner and clearer to read. sprintf is very much a c-style thing, and those not coming from c often won't have any idea what %s is doing in a URL in those constants.

Do you think you could make the change so those methods instead return:

```php
return "https://{$this->region}.battle.net/oauth/token"
```

**Comment by gsdevme** [comment]
Well I do it mainly from a Symfony background, that and because its a constant. Its a fixed string. That kind of concatenation seems old school in PHP if you ask me

**Comment by tpavlek** [comment]
This was resolved in the latest commit.

**Comment by gsdevme** [comment]
Thanks

**Pull request closed without merging**
